### ISSUE TITLE
Server Database location

### ISSUE THREAD

**Issue by segallis** [MajorMJR/temperature-logger-esp8266-micropython#1]
I see in your code you log the temperature to a database on a server at http://10.42.100.1:8086/write?db=temperature, but I don;t understand what that server is?  Is that a public server or your own?  Do you have any info on how to set that server database up?

Thanks,
-Greg

**Comment by mroote** [comment]
Hi Greg,

It's not too clear in the code but that is an influxdb server I had setup to post data. It's a time series database that you can use HTTP requests to send data to record. I was using the urequest library in micropython to make the POST request to influxdb to record the temperature at that time.

There's lots of documentation here: https://docs.influxdata.com/influxdb/v1.8/introduction/install/ if you're interested in setting the database up for yourself.


Mitch
